---
name: ci 

on:
  push:
    paths-ignore:
      - "README.md"
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Configure CMake
        run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build
      - name: Build
        working-directory: build
        run: cmake --build .
      - name: Upload static lib
        uses: actions/upload-artifact@v2
        with:
          name: libgpio-static.a
          path: ${{github.workspace}}/build/bin/
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: install dependancies
        run: python3 -m pip install gcovr && sudo apt install tree
      - name: Configure CMake
        run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug
      - name: Build
        working-directory: build
        run: cmake --build .
      - name: Test
        working-directory: build
        run: GTEST_OUTPUT=xml:results/ GTEST_COLOR=1 ctest -V
      - name: Upload test results on failure
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: results_xml
          path: ${{github.workspace}}/build/results/**/*.xml
      - name: gcov
        working-directory: build
        run: make cov
      - name: debug
        working-directory: build
        run: |
          tree
          cat /home/runner/work/gpio/gpio/build/tests/CMakeFiles/test_sysfs.dir/test_sysfs.cpp.gcda
      - name: codecov push
        uses: codecov/codecov-action@v1
        with:
          files: ${{github.workspace}}/build/cov.xml
  cppcheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: install cppcheck
        run: sudo apt install cppcheck -y
      - name: Execute cppcheck
        run: cppcheck src include
